/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    CreateTenant: () => import('#controllers/admin/create_tenant_controller'),
    DestroyTenant: () => import('#controllers/admin/destroy_tenant_controller'),
    ListTenants: () => import('#controllers/admin/list_tenants_controller'),
    UpdateTenant: () => import('#controllers/admin/update_tenant_controller'),
  },
  auth: {
    AccessToken: () => import('#controllers/auth/access_token_controller'),
  },
  client: {
    CreateClient: () => import('#controllers/client/create_client_controller'),
    DestroyClient: () => import('#controllers/client/destroy_client_controller'),
    ListClients: () => import('#controllers/client/list_clients_controller'),
    ShowClient: () => import('#controllers/client/show_client_controller'),
    UpdateClient: () => import('#controllers/client/update_client_controller'),
  },
  user: {
    CreateUser: () => import('#controllers/user/create_user_controller'),
    DestroyUser: () => import('#controllers/user/destroy_user_controller'),
    ListUsers: () => import('#controllers/user/list_users_controller'),
    ShowUser: () => import('#controllers/user/show_user_controller'),
    UpdateUser: () => import('#controllers/user/update_user_controller'),
  },
}
