/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    CreateGym: () => import('#controllers/admin/create_gym_controller'),
    DestroyGym: () => import('#controllers/admin/destroy_gym_controller'),
    ListGyms: () => import('#controllers/admin/list_gyms_controller'),
    UpdateGym: () => import('#controllers/admin/update_gym_controller'),
  },
  auth: {
    AccessToken: () => import('#controllers/auth/access_token_controller'),
    Testing: () => import('#controllers/auth/testing_controller'),
  },
  user: {
    CreateUser: () => import('#controllers/user/create_user_controller'),
    DestroyUser: () => import('#controllers/user/destroy_user_controller'),
    ListUsers: () => import('#controllers/user/list_users_controller'),
    ShowUser: () => import('#controllers/user/show_user_controller'),
    UpdateUser: () => import('#controllers/user/update_user_controller'),
  },
}
