/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AttendanceSchema extends BaseModel {
  static $columns = [
    'id',
    'gymId',
    'clientId',
    'membershipId',
    'checkIn',
    'checkOut',
    'accessGranted',
    'notes',
    'createdAt',
  ] as const
  $columns = AttendanceSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare gymId: bigint | number
  @column()
  declare clientId: bigint | number
  @column()
  declare membershipId: bigint | number | null
  @column.dateTime()
  declare checkIn: DateTime
  @column.dateTime()
  declare checkOut: DateTime | null
  @column()
  declare accessGranted: boolean
  @column()
  declare notes: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'id',
    'tokenableId',
    'type',
    'name',
    'hash',
    'abilities',
    'createdAt',
    'updatedAt',
    'lastUsedAt',
    'expiresAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare tokenableId: bigint | number
  @column()
  declare type: string
  @column()
  declare name: string | null
  @column()
  declare hash: string
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
}

export class ClientSchema extends BaseModel {
  static $columns = [
    'id',
    'gymId',
    'fullName',
    'phone',
    'email',
    'birthDate',
    'gender',
    'address',
    'emergencyContactName',
    'emergencyContactPhone',
    'notes',
    'status',
    'createdAt',
    'updatedAt',
  ] as const
  $columns = ClientSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare gymId: bigint | number
  @column()
  declare fullName: string
  @column()
  declare phone: string | null
  @column()
  declare email: string | null
  @column.date()
  declare birthDate: DateTime | null
  @column()
  declare gender: string | null
  @column()
  declare address: string | null
  @column()
  declare emergencyContactName: string | null
  @column()
  declare emergencyContactPhone: string | null
  @column()
  declare notes: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class GymSchema extends BaseModel {
  static $columns = [
    'id',
    'name',
    'slug',
    'logoUrl',
    'primaryColor',
    'secondaryColor',
    'accentColor',
    'email',
    'phone',
    'address',
    'status',
    'createdAt',
    'updatedAt',
  ] as const
  $columns = GymSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare logoUrl: string | null
  @column()
  declare primaryColor: string | null
  @column()
  declare secondaryColor: string | null
  @column()
  declare accentColor: string | null
  @column()
  declare email: string | null
  @column()
  declare phone: string | null
  @column()
  declare address: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MembershipSchema extends BaseModel {
  static $columns = [
    'id',
    'gymId',
    'clientId',
    'planId',
    'startDate',
    'endDate',
    'finalPrice',
    'status',
    'paymentStatus',
    'notes',
    'createdBy',
    'createdAt',
    'updatedAt',
  ] as const
  $columns = MembershipSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare gymId: bigint | number
  @column()
  declare clientId: bigint | number
  @column()
  declare planId: bigint | number
  @column.date()
  declare startDate: DateTime
  @column.date()
  declare endDate: DateTime
  @column()
  declare finalPrice: string
  @column()
  declare status: string
  @column()
  declare paymentStatus: string
  @column()
  declare notes: string | null
  @column()
  declare createdBy: bigint | number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PaymentSchema extends BaseModel {
  static $columns = [
    'id',
    'gymId',
    'membershipId',
    'clientId',
    'amount',
    'paymentDate',
    'paymentMethod',
    'reference',
    'notes',
    'receivedBy',
    'createdAt',
    'updatedAt',
  ] as const
  $columns = PaymentSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare gymId: bigint | number
  @column()
  declare membershipId: bigint | number
  @column()
  declare clientId: bigint | number
  @column()
  declare amount: string
  @column.dateTime()
  declare paymentDate: DateTime
  @column()
  declare paymentMethod: string
  @column()
  declare reference: string | null
  @column()
  declare notes: string | null
  @column()
  declare receivedBy: bigint | number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PlanSchema extends BaseModel {
  static $columns = [
    'id',
    'gymId',
    'name',
    'description',
    'planType',
    'durationDays',
    'price',
    'status',
    'createdAt',
    'updatedAt',
  ] as const
  $columns = PlanSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare gymId: bigint | number
  @column()
  declare name: string
  @column()
  declare description: string | null
  @column()
  declare planType: string
  @column()
  declare durationDays: number
  @column()
  declare price: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = [
    'id',
    'gymId',
    'fullName',
    'email',
    'password',
    'role',
    'status',
    'createdAt',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare gymId: bigint | number
  @column()
  declare fullName: string
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
