export enum Status {
  ACTIVE = 'Activo',
  INACTIVE = 'Inactivo',
  PENDING = 'Pendiente',
  SUSPENDED = 'Suspendido',
  EXPIRED = 'Expirado',
  CANCELLED = 'Cancelado',
  FROZEN = 'Congelado',
  PAID = 'Pagado',
  REFUNDED = 'Reembolsado',
  CHECKED_IN = 'Checkin',
  CHECKED_OUT = 'Checkout',
  DENIED = 'Denegado',
  PENDING_REVIEW = 'Pendiente de revisión',
  APPROVED = 'Aprobado',
  REJECTED = 'Rechazado',
  ARCHIVED = 'Archivado',
  DRAFT = 'Borrador',
  COMPLETED = 'Completado',
}
